/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Clipboard: typeof import('./src/utils/clipboard.ts')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileIcon: typeof import('./src/utils/fileIcon.ts')['default']
    FileInfoModal: typeof import('./src/components/FileInfoModal.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    FileStore: typeof import('./src/stores/fileStore.ts')['default']
    FormatBytes: typeof import('./src/utils/formatBytes.ts')['default']
    ImagePreviewModal: typeof import('./src/components/ImagePreviewModal.vue')['default']
    Main: typeof import('./src/main.ts')['default']
    NewFolderDialog: typeof import('./src/components/NewFolderDialog.vue')['default']
    Path: typeof import('./src/utils/path.ts')['default']
    Previewable: typeof import('./src/utils/previewable.ts')['default']
    QrCodeModal: typeof import('./src/components/QrCodeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Shims.d': typeof import('./src/types/shims.d.ts')['default']
    SyntaxHighlight: typeof import('./src/utils/syntaxHighlight.ts')['default']
    TextPreviewModal: typeof import('./src/components/TextPreviewModal.vue')['default']
    Types: typeof import('./src/types/index.ts')['default']
    UploadModal: typeof import('./src/components/UploadModal.vue')['default']
    UrlDownloadModal: typeof import('./src/components/UrlDownloadModal.vue')['default']
    UseFileApi: typeof import('./src/composables/useFileApi.ts')['default']
    UseTheme: typeof import('./src/composables/useTheme.ts')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    'ViteEnv.d': typeof import('./src/vite-env.d.ts')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
